### ISSUE TITLE
Fix Behat builds and re-enable

### ISSUE THREAD

**Issue by chillu** [silverstripe/bambusa-installer#21]
https://travis-ci.org/silverstripe/bambusa-installer/builds/555592235 broke the build, because I merged https://github.com/silverstripe/bambusa-installer/pull/14 on red. Sorry about that!

The root cause here is that the new modal breaks Behat login behaviour. Since that's in core, it's not an easy fix. We either need to make this logic extensible by modules, or copy some of those tests to the bambusa installer as dedicated smoke tests (increasing our test maintenance surface).

Given that we test most modules used in Bambusa in isolation through Behat already, and even in combination through `silverstripe/installer` level smoke tests, I think spending time to fix these tests is relatively low value. We're not performing heavy CMS customisations, so I wouldn't expect things like "publish a page" to break when we're relying on stable versions of those modules.

See PR to disable (not fix) Behat builds at https://github.com/silverstripe/bambusa-installer/pull/22

**Comment by dnsl48** [comment]
Fixed through https://github.com/silverstripe/bambusa-installer/pull/23
