### ISSUE TITLE
SEO module breaks history view

### ISSUE THREAD

**Issue by chillu** [silverstripe/bambusa-installer#43]
@chillu commented on [Tue Jul 30 2019](https://github.com/silverstripe/silverstripe-asset-admin/issues/972)

When viewing a single version (not the version list)

![image.png](https://images.zenhubusercontent.com/52b2f46cf0808b12020000f7/294e1403-2752-4e3e-9f92-24891111f7b3)

**Comment by bergice** [comment]
Closing as we're removing the module as it's causing too many problems.
