### ISSUE TITLE
Banner block link broken

### ISSUE THREAD

**Issue by chillu** [silverstripe/bambusa-installer#53]
Moved from https://github.com/silverstripe/silverstripe-elemental-bannerblock/issues/28. Probably bambusa specific so moving in here rather than the module

# Pull request
* [x] https://github.com/silverstripe/silverstripe-admin/pull/921
* [x] https://github.com/silverstripe/bambusa-installer/pull/59 (update composer.lock)

**Comment by dnsl48** [comment]
we'll need to make a patch release of `silverstripe/admin` module

**Comment by dnsl48** [comment]
released

**Comment by dnsl48** [comment]
deployed to UAT
