### ISSUE TITLE
Search is failing on some demos

### ISSUE THREAD

**Issue by chillu** [silverstripe/bambusa-installer#69]
Doesn't throw an error, but also doesn't show any results.
Example: https://ragingstags-sscom.demo.silverstripe.cc/search?q=contact
Might be intermittent?

**Comment by dnsl48** [comment]
Could be related to https://github.com/silverstripe/bambusa-installer/issues/71
Will retest this after #71 gets fixed.

**Comment by dnsl48** [comment]
Caused by https://github.com/silverstripeltd/open-sourcerers/issues/129

**Comment by dnsl48** [comment]
fixed (for new demos)

**Comment by dnsl48** [comment]
Well... after both https://github.com/silverstripeltd/open-sourcerers/issues/129 and https://github.com/silverstripe/bambusa-installer/issues/71 are fixed, search still not showing any results (though not returning 500s anymore).
Seems like there may be another cause yet.

**Comment by dnsl48** [comment]
Addressed by disabling search due to infrastructure problems
 - https://github.com/silverstripe/bambusa-installer/pull/81
 - https://github.com/silverstripe/bambusa-theme/pull/54

More details at https://silverstripe.atlassian.net/wiki/spaces/BAM/pages/813367881/Bambusa+Search+issues
