### ISSUE TITLE
Some demos are missing assets

### ISSUE THREAD

**Issue by chillu** [silverstripe/bambusa-installer#70]
https://salesopscmsdemo-sscom.demo.silverstripe.cc/assets/Banner-images/Hero-banner__FillWzE5MjAsMTA4MF0.png
Doesn't work: https://ragingstags-sscom.demo.silverstripe.cc/assets/Banner-images/Hero-banner__FillWzE5MjAsMTA4MF0.png

**Comment by dnsl48** [comment]
https://ragingstags-sscom.demo.silverstripe.cc/assets/Banner-images/Hero-banner__FillWzE5MjAsMTA4MF0.png seems to be working for me now.

**Comment by dnsl48** [comment]
Caused by https://github.com/silverstripeltd/open-sourcerers/issues/129
