### ISSUE TITLE
Add validation on the demo name length

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/bambusa-installer#87]
Has to be no more than 34 characters

https://app.raygun.com/crashreporting/1po60pm/errors/3843399834?correlationId=163814453035&occurredOn=2019-10-03T00:45:54.0000000Z#51721241689

**Comment by chillu** [comment]
This has caused multiple demo failures already, which aren't recovering well - you simply won't get a confirmation email. Really bad first user experience, so a high priority to fix.
